# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabira_web', '0005_event_max_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='form',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='deviation',
            name='da_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='deviation',
            name='fav_me_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='feed',
            name='type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='parent',
            field=models.CharField(blank=True, default='', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, default='http://www.talesoftabira.com/wiki/Items'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='custom_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='cameos',
            field=models.CharField(default='No', max_length=12),
        ),
        migrations.AlterField(
            model_name='team',
            name='tumblr',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='type',
            field=models.CharField(blank=True, default='Drawn', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip',
            field=models.GenericIPAddressField(default=''),
        ),
    ]
